# Generated by Django 5.0 on 2025-10-18 14:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, verbose_name='Nom du lieu')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Ex: 49.158889', max_digits=9, null=True, verbose_name='Latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Ex: 5.883333', max_digits=9, null=True, verbose_name='Longitude')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/lieux/', verbose_name='Photo du lieu')),
                ('capacite', models.IntegerField(blank=True, help_text='Nombre maximum de personnes', null=True, verbose_name='Capacité')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Lieu',
                'verbose_name_plural': 'Lieux',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeEvenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du type')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('couleur', models.CharField(default='#3B82F6', help_text='Code couleur hexadécimal (ex: #3B82F6)', max_length=7, verbose_name='Couleur')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: calendar, plane, users)", max_length=50, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text="Décocher pour désactiver ce type d'événement", verbose_name='Actif')),
            ],
            options={
                'verbose_name': "Type d'événement",
                'verbose_name_plural': "Types d'événements",
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug')),
                ('description', models.TextField(verbose_name='Description')),
                ('description_courte', models.CharField(blank=True, help_text='Résumé pour le calendrier', max_length=200, verbose_name='Description courte')),
                ('lieu_details', models.CharField(blank=True, help_text='Ex: Salle 3, Piste Nord, etc.', max_length=200, verbose_name='Précisions sur le lieu')),
                ('date_debut', models.DateTimeField(verbose_name='Date et heure de début')),
                ('date_fin', models.DateTimeField(verbose_name='Date et heure de fin')),
                ('journee_complete', models.BooleanField(default=False, help_text="Cocher si l'événement dure toute la journée", verbose_name='Journée complète')),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('termine', 'Terminé')], default='planifie', max_length=10, verbose_name='Statut')),
                ('inscription_requise', models.BooleanField(default=False, verbose_name='Inscription requise')),
                ('places_limitees', models.BooleanField(default=False, verbose_name='Places limitées')),
                ('nombre_places', models.IntegerField(blank=True, help_text='Laisser vide si illimité', null=True, verbose_name='Nombre de places')),
                ('date_limite_inscription', models.DateTimeField(blank=True, null=True, verbose_name="Date limite d'inscription")),
                ('public', models.BooleanField(default=True, help_text='Visible par tous (même non-membres)', verbose_name='Public')),
                ('membres_seulement', models.BooleanField(default=False, help_text='Visible uniquement par les membres connectés', verbose_name='Membres uniquement')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/evenements/%Y/%m/', verbose_name='Image')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('vues', models.IntegerField(default=0, editable=False, verbose_name='Nombre de vues')),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evenements_organises', to=settings.AUTH_USER_MODEL, verbose_name='Organisateur')),
                ('lieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evenements', to='events.lieu', verbose_name='Lieu')),
                ('type_evenement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evenements', to='events.typeevenement', verbose_name="Type d'événement")),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="Date d'inscription")),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('annule', 'Annulé'), ('liste_attente', "Liste d'attente")], default='en_attente', max_length=15, verbose_name='Statut')),
                ('nombre_accompagnants', models.IntegerField(default=0, help_text='Personnes accompagnant le participant', verbose_name="Nombre d'accompagnants")),
                ('commentaire', models.TextField(blank=True, help_text='Message ou demande particulière', verbose_name='Commentaire')),
                ('present', models.BooleanField(default=False, help_text="Cocher après l'événement si le participant était présent", verbose_name='Présent')),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='events.evenement', verbose_name='Événement')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions_evenements', to=settings.AUTH_USER_MODEL, verbose_name='Participant')),
            ],
            options={
                'verbose_name': 'Inscription',
                'verbose_name_plural': 'Inscriptions',
                'ordering': ['date_inscription'],
                'indexes': [models.Index(fields=['evenement', 'statut'], name='events_insc_eveneme_0d6fd4_idx')],
                'unique_together': {('evenement', 'participant')},
            },
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['date_debut'], name='events_even_date_de_54bf5b_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['statut'], name='events_even_statut_33a279_idx'),
        ),
        migrations.AddIndex(
            model_name='evenement',
            index=models.Index(fields=['type_evenement'], name='events_even_type_ev_324735_idx'),
        ),
    ]
