# Generated by Django 5.0 on 2025-10-18 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(blank=True, max_length=100, verbose_name='Prénom')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('telephone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone')),
                ('sujet', models.CharField(choices=[('info', "Demande d'information"), ('adhesion', 'Adhésion au club'), ('evenement', 'Question sur un événement'), ('technique', 'Question technique'), ('partenariat', 'Proposition de partenariat'), ('autre', 'Autre')], default='info', max_length=20, verbose_name='Sujet')),
                ('message', models.TextField(verbose_name='Message')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text="Adresse IP de l'expéditeur", null=True, verbose_name='Adresse IP')),
                ('statut', models.CharField(choices=[('nouveau', 'Nouveau'), ('en_cours', 'En cours de traitement'), ('traite', 'Traité'), ('archive', 'Archivé')], default='nouveau', max_length=10, verbose_name='Statut')),
                ('date_traitement', models.DateTimeField(blank=True, null=True, verbose_name='Date de traitement')),
                ('lu', models.BooleanField(default=False, verbose_name='Lu')),
                ('reponse', models.TextField(blank=True, help_text='Réponse apportée au message (usage interne)', verbose_name='Réponse')),
                ('repondu', models.BooleanField(default=False, verbose_name='Répondu')),
                ('date_reponse', models.DateTimeField(blank=True, null=True, verbose_name='Date de réponse')),
                ('notes', models.TextField(blank=True, help_text='Notes administratives (non visibles par le contact)', verbose_name='Notes internes')),
            ],
            options={
                'verbose_name': 'Message de contact',
                'verbose_name_plural': 'Messages de contact',
                'ordering': ['-date_envoi'],
                'indexes': [models.Index(fields=['statut', 'lu'], name='core_contac_statut_12bbaf_idx'), models.Index(fields=['-date_envoi'], name='core_contac_date_en_8c18ed_idx')],
            },
        ),
    ]
