# Generated by Django 5.0 on 2025-11-02 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, verbose_name='URL visitée')),
                ('ip_address', models.GenericIPAddressField(verbose_name='Adresse IP')),
                ('user_agent', models.CharField(blank=True, help_text="Navigateur et système d'exploitation", max_length=500, verbose_name='User Agent')),
                ('referer', models.CharField(blank=True, help_text="Page d'origine de la visite", max_length=500, verbose_name='Référent')),
                ('session_key', models.CharField(blank=True, max_length=40, verbose_name='Clé de session')),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Date et heure')),
                ('response_time', models.IntegerField(blank=True, help_text='Temps de traitement de la requête en millisecondes', null=True, verbose_name='Temps de réponse (ms)')),
                ('user', models.ForeignKey(blank=True, help_text='Utilisateur connecté (si authentifié)', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Page vue',
                'verbose_name_plural': 'Pages vues',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'url'], name='analytics_p_timesta_806105_idx'), models.Index(fields=['ip_address', 'timestamp'], name='analytics_p_ip_addr_f9d0af_idx')],
            },
        ),
    ]
