# Generated by Django 5.0 on 2025-10-18 15:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieLien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('icone', models.CharField(blank=True, help_text="Nom de l'icône (ex: globe, link, star)", max_length=50, verbose_name='Icône')),
                ('ordre', models.IntegerField(default=0, help_text='Les catégories avec un ordre plus petit apparaissent en premier', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour masquer cette catégorie', verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Catégorie de lien',
                'verbose_name_plural': 'Catégories de liens',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Lien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre du lien')),
                ('url', models.URLField(help_text='URL complète (ex: https://www.example.com)', max_length=500, validators=[django.core.validators.URLValidator()], verbose_name='URL')),
                ('description', models.TextField(blank=True, help_text='Description du site ou de la ressource', verbose_name='Description')),
                ('logo', models.ImageField(blank=True, help_text="Logo ou capture d'écran du site", null=True, upload_to='weblinks/logos/', verbose_name='Logo du site')),
                ('date_ajout', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('ordre', models.IntegerField(default=0, help_text='Les liens avec un ordre plus petit apparaissent en premier', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour masquer ce lien', verbose_name='Actif')),
                ('featured', models.BooleanField(default=False, help_text='Cocher pour mettre ce lien en avant', verbose_name='Mis en avant')),
                ('ouvrir_nouvel_onglet', models.BooleanField(default=True, help_text='Ouvre le lien dans un nouvel onglet par défaut', verbose_name='Ouvrir dans un nouvel onglet')),
                ('nombre_clics', models.IntegerField(default=0, editable=False, verbose_name='Nombre de clics')),
                ('tags', models.CharField(blank=True, help_text='Mots-clés séparés par des virgules (ex: planeur, thermique, moteur)', max_length=200, verbose_name='Tags')),
                ('notes', models.TextField(blank=True, help_text='Notes internes (non visibles publiquement)', verbose_name='Notes')),
                ('ajout_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liens_ajoutes', to=settings.AUTH_USER_MODEL, verbose_name='Ajouté par')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liens', to='weblinks.categorielien', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Lien',
                'verbose_name_plural': 'Liens',
                'ordering': ['categorie__ordre', 'ordre', 'titre'],
                'indexes': [models.Index(fields=['categorie', 'actif'], name='weblinks_li_categor_401c80_idx'), models.Index(fields=['featured'], name='weblinks_li_feature_00af4b_idx')],
            },
        ),
    ]
