# Generated by Django 5.0 on 2025-10-18 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, help_text='Les catégories avec un ordre plus petit apparaissent en premier', verbose_name="Ordre d'affichage")),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du tag')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name='Titre')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug (URL)')),
                ('contenu', models.TextField(help_text="Contenu de l'article (supporte le HTML)", verbose_name='Contenu')),
                ('extrait', models.TextField(blank=True, help_text='Résumé court pour la liste des articles (généré auto si vide)', max_length=300, verbose_name='Extrait')),
                ('image', models.ImageField(blank=True, help_text="Image principale de l'article", null=True, upload_to='blog/articles/%Y/%m/', verbose_name='Image à la une')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('date_publication', models.DateTimeField(blank=True, null=True, verbose_name='Date de publication')),
                ('statut', models.CharField(choices=[('brouillon', 'Brouillon'), ('publie', 'Publié')], default='brouillon', max_length=10, verbose_name='Statut')),
                ('vues', models.IntegerField(default=0, editable=False, verbose_name='Nombre de vues')),
                ('meta_description', models.CharField(blank=True, help_text='Description pour les moteurs de recherche (max 160 car.)', max_length=160, verbose_name='Meta description')),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='Auteur')),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='articles', to='blog.categorie', verbose_name='Catégorie')),
                ('tags', models.ManyToManyField(blank=True, related_name='articles', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
                'ordering': ['-date_publication', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur_nom', models.CharField(max_length=100, verbose_name="Nom de l'auteur")),
                ('auteur_email', models.EmailField(max_length=254, verbose_name="Email de l'auteur")),
                ('contenu', models.TextField(verbose_name='Commentaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('approuve', models.BooleanField(default=False, help_text="Les commentaires doivent être approuvés avant d'apparaître", verbose_name='Approuvé ?')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentaires', to='blog.article', verbose_name='Article')),
                ('auteur_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commentaires', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='blog.commentaire', verbose_name='Réponse à')),
            ],
            options={
                'verbose_name': 'Commentaire',
                'verbose_name_plural': 'Commentaires',
                'ordering': ['date_creation'],
                'indexes': [models.Index(fields=['article', 'approuve'], name='blog_commen_article_15c223_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['-date_publication'], name='blog_articl_date_pu_587a62_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['statut'], name='blog_articl_statut_3c1ce1_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['slug'], name='blog_articl_slug_cc8df7_idx'),
        ),
    ]
