# Generated by Django 5.0 on 2025-10-29 11:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='contenu',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text="Contenu de l'article avec éditeur WYSIWYG et upload d'images", verbose_name='Contenu'),
        ),
    ]
