# Generated by Django 5.0 on 2025-10-18 14:59

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FonctionBureau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom de la fonction')),
                ('description', models.TextField(blank=True, help_text='Responsabilités et missions de cette fonction', verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, help_text="Ordre d'affichage dans la liste du bureau", verbose_name="Ordre d'affichage")),
                ('email_contact', models.EmailField(blank=True, help_text='Email générique pour cette fonction (ex: president@amcd57.fr)', max_length=254, verbose_name='Email de contact')),
                ('actif', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Fonction bureau',
                'verbose_name_plural': 'Fonctions bureau',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='TypeMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, unique=True, verbose_name='Nom du type')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('ordre', models.IntegerField(default=0, help_text='Les types avec un ordre plus petit apparaissent en premier', verbose_name="Ordre d'affichage")),
                ('actif', models.BooleanField(default=True, help_text='Décocher pour désactiver ce type', verbose_name='Actif')),
                ('peut_voter', models.BooleanField(default=True, help_text='Droit de vote aux assemblées', verbose_name='Peut voter')),
                ('acces_terrain', models.BooleanField(default=True, help_text='Peut accéder au terrain de vol', verbose_name='Accès terrain')),
                ('acces_espace_membre', models.BooleanField(default=True, help_text="Accès à l'espace membre du site", verbose_name='Accès espace membre')),
            ],
            options={
                'verbose_name': 'Type de membre',
                'verbose_name_plural': 'Types de membres',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ProfilMembre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction_active', models.BooleanField(default=False, help_text='Cocher si le membre exerce actuellement sa fonction au bureau', verbose_name='Fonction active')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Photo de profil')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('telephone', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone')),
                ('telephone_portable', models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Le numéro de téléphone doit être au format: '+999999999'. 9 à 15 chiffres.", regex='^\\+?1?\\d{9,15}$')], verbose_name='Téléphone portable')),
                ('adresse', models.CharField(blank=True, max_length=255, verbose_name='Adresse')),
                ('code_postal', models.CharField(blank=True, max_length=10, verbose_name='Code postal')),
                ('ville', models.CharField(blank=True, max_length=100, verbose_name='Ville')),
                ('pays', models.CharField(default='France', max_length=100, verbose_name='Pays')),
                ('bio', models.TextField(blank=True, help_text='Présentation du membre', verbose_name='Biographie')),
                ('experience_aeromodelisme', models.TextField(blank=True, help_text='Années de pratique, spécialités, etc.', verbose_name='Expérience en aéromodélisme')),
                ('niveau', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé'), ('expert', 'Expert')], default='debutant', max_length=15, verbose_name='Niveau')),
                ('specialites', models.CharField(blank=True, help_text='Ex: Planeur, Thermique, Voltige, etc. (séparés par des virgules)', max_length=200, verbose_name='Spécialités')),
                ('avions_possedes', models.TextField(blank=True, help_text='Liste des modèles possédés', verbose_name='Avions possédés')),
                ('numero_licence_ffam', models.CharField(blank=True, help_text="Fédération Française d'Aéromodélisme", max_length=50, verbose_name='Numéro de licence FFAM')),
                ('date_validite_licence', models.DateField(blank=True, null=True, verbose_name='Date de validité de la licence')),
                ('assurance_valide', models.BooleanField(default=False, help_text="L'assurance RC est-elle à jour ?", verbose_name='Assurance valide')),
                ('date_adhesion', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'adhésion au club")),
                ('cotisation_a_jour', models.BooleanField(default=False, verbose_name='Cotisation à jour')),
                ('date_fin_cotisation', models.DateField(blank=True, null=True, verbose_name='Date de fin de cotisation')),
                ('newsletter', models.BooleanField(default=True, help_text='Recevoir la newsletter du club', verbose_name='Newsletter')),
                ('notifications_evenements', models.BooleanField(default=True, help_text="Recevoir les notifications d'événements", verbose_name='Notifications événements')),
                ('profil_public', models.BooleanField(default=False, help_text='Rendre le profil visible publiquement', verbose_name='Profil public')),
                ('site_web', models.URLField(blank=True, verbose_name='Site web personnel')),
                ('youtube', models.URLField(blank=True, verbose_name='Chaîne YouTube')),
                ('facebook', models.URLField(blank=True, verbose_name='Profil Facebook')),
                ('instagram', models.CharField(blank=True, help_text="Nom d'utilisateur Instagram (sans @)", max_length=100, verbose_name='Instagram')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création du profil')),
                ('date_modification', models.DateTimeField(auto_now=True, verbose_name='Dernière modification')),
                ('notes_admin', models.TextField(blank=True, help_text='Notes internes (non visibles par le membre)', verbose_name='Notes administratives')),
                ('fonction_bureau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profils', to='members.fonctionbureau', verbose_name='Fonction au bureau')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
                ('type_membre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='profils', to='members.typemembre', verbose_name='Type de membre')),
            ],
            options={
                'verbose_name': 'Profil membre',
                'verbose_name_plural': 'Profils membres',
                'ordering': ['user__last_name', 'user__first_name'],
                'indexes': [models.Index(fields=['type_membre'], name='members_pro_type_me_e387be_idx'), models.Index(fields=['fonction_bureau'], name='members_pro_fonctio_0d6b10_idx'), models.Index(fields=['cotisation_a_jour'], name='members_pro_cotisat_1958b1_idx')],
            },
        ),
    ]
