# Generated by Django 5.0 on 2025-10-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilmembre',
            name='numero_licence_ffam',
        ),
        migrations.AddField(
            model_name='profilmembre',
            name='numero_licence_ufolep',
            field=models.CharField(blank=True, help_text="Union Française des Œuvres Laïques d'Éducation Physique", max_length=50, verbose_name='Numéro de licence UFOLEP'),
        ),
    ]
